# Left half: central role, USB to PC

# Split
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1

# USB
CONFIG_ZMK_USB=y

# BLE
CONFIG_ZMK_BLE=y


# RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# Mouse / pointing (receives trackball data from peripheral)
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y

# Power management
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
